### ISSUE TITLE
Rejecting a signed up user will make it enabled instead.

### ISSUE THREAD

**Issue by cleydyr** [debiki/talkyard#26]
## Steps to reproduce

1. Signup for a new account
1. Login as administrator
1. Go to Admin Area | Users | Waiting 
1. Find the new account and reject it
1. Check the Enabled tab

## Current behavior
The user appears among the enabled users

## Expected behavior
The user shouldn't appear as it has been rejected

**Comment by kajmagnus** [comment]
Thanks for reporting this.  Right now, seems to me that the bug is that the Approve and Reject buttons are visible. In your case, shouldn't have been possible to click Reject at all, because ....

... There's this setting:  **Approve users.** *New users need to be approved by staff before they can access the site.* (In the Admin Area, the Settings tab, in Signup and Login).

... and I think in your case, that setting is not enabled? That means that users *can* access the site and post comments, without approval. And in this case, approving or rejecting users ... doesn't mean anything, because approval = not required.

I tested locally, and if I do enable **Approve users**, then a user that I rejected, is thereafter unable to access the site. So, seems to work properly, with that setting enabled.

So, what I'm planning to do: I'll remove the whole *Waiting* tab (incl Approve or Reject buttons) when **Approve users** is not enabled.

(At the same time, I'll add more tabs: staff users, suspended users, & new users (sorted by recently joined first).)

What do you think? / or maybe I'm misunderstanding / overlooking sth

**Comment by cleydyr** [comment]
> and I think in your case, that setting is not enabled?
No. It isn't. Good catch.

Indeed this seems to be a bug that the Waiting tab appears **and** that it contains users to be approved. It would be a good idea to check why they appear in the first place (how the condition "waiting to be approved" is calculated).

Regards.

**Comment by kajmagnus** [comment]
(I've fixed this ... and it's in a different branch (`w-km5` — I started working in my own work-in-progress branches instead, where I can tidy up the history before merging to `master`), I'll merge it in a few days ... and release a new version probably at the end of this week.)

**Comment by kajmagnus** [comment]
Now your server should have auto upgraded to version `v0.6.7-WIP-6-0cc6df74e` with this bug fixed. Would you like to see if it works for you?

**Comment by cleydyr** [comment]
I didn't have the opportunity to manually test it. You can close it for now.

Thank you!

**Comment by kajmagnus** [comment]
Ok, hmm, yes step 3: `Go to Admin Area | Users | Waiting` cannot be done any longer because the Waiting tab is now gone (unless one has enabled `Approve users [ ] New users need to be approved by staff`).

Thanks for reporting.
