### ISSUE TITLE
Add Brazilian Portuguese to the available translations

### ISSUE THREAD

**Issue by cleydyr** [debiki/talkyard#29]
Sent as https://github.com/debiki/talkyard/pull/28

Regards

**Comment by kajmagnus** [comment]
Hello @cleydyr! Thanks for the PR.  Can I ask, what was your workflow for doing the translations?  I mean, in each file, one sees only one single language at a time. So once one has started translating a sentence ... the original English text kind of disappears. What did you think about that? Or maybe you did like I do  ...

... I'm using a diff tool named Meld, when translating: (I've started a bit for Swedish)

`meld translations/en/i18n.ts translations/sv/i18n.ts`

then, to the left, I see the English version, and to the right, the Swedish, compared line by line, & can edit.

Probably I should add a tips about this at the top of the translation files :- )

I'll take a closer look tomorrow.

**Comment by cleydyr** [comment]
Hey, @kajmagnus. I just looked at the English string and put the Portuguese translation inside the double quotes, before the English part. Once I had finished writing the Portuguese I removed the English part afterwards. Yeah, this is rough. :D

**Comment by cleydyr** [comment]
Oh! Looking at the PR I see I've lost some entries. I'll add some commits to cover those soon. ;)

**Comment by kajmagnus** [comment]
Hi again Cleydyr, earlier today, I added a Contributor License Agreement. Would you like to have a look? It's in the main repo, see below (it'll appear after `git fetch ; ... `).

And squash the commits?

And agree with the CLA? By adding this to the commit message: (& replacing with your name)

>  I, Your Full Name <your@<i></i>email.address>, agree to the Contributor License Agreement, docs/CLA-v1.txt.

These Git commands should work: (I tested locally)

```
# Fetch the CLA:
git remote add upstream https://github.com/debiki/talkyard.git
git fetch upstream master
git checkout master
git merge --ff-only upstream/master

#   --->  Now you can read the CLA, it appeared here:  ./docs/CLA-v1.txt

# Rebase:
git tag before-rebase  # in case something goes wrong
git checkout pt-br-translation
git rebase master

# Squash:
git reset master
git add translations/
git commit -m " .... I ... agree to the CLA ..."
```

**Comment by cleydyr** [comment]
I'll have a look at those later today.

Regards.

**Comment by kajmagnus** [comment]
Ok thanks :- ) I'll merge tomorrow (just finishing reviewing some of my own code)

**Comment by kajmagnus** [comment]
Status update: I added a script that checks the translated values for whitespace and punctuation typos ... (which almost certainly happens when editing that many different fields :- ))

... and ran the script against the translations, and found a few typos that I have now fixed.

(If you're curious, here're the fixes: https://github.com/debiki/talkyard/commit/ad0fa1578d619f3ba8ca6ce79c7a1296fb562a1c  — if you scroll down to the `translations/pt_BR/i18n.ts` file )

(here're the script: https://github.com/debiki/talkyard/commit/53b363b77eb69f7b7d526658c88fa1482b29b3a9#diff-a1cf6d24c09d0ee8e4aa9190ba0b94eeR73  )

I've tested locally, all works fine (well I don't know Spanish, but looks nice in Google Translate :- )).
(Currently finishing reviewing some of my own other unrelated code ...)

**Comment by cleydyr** [comment]
Hey, @kajmagnus. Portuguese and Spanish, despite related, are completely different languages. It's kinda similar to how Swedish and Danish are related. ;)

Regarding the typos: Yeah, they are to be expected, but maybe we could avoid updating the script and just avoid trailing whitespaces (that must remain fix and it's enforced by your script) by encoding it on the source code itself. Or just avoid breaking phrases altogether and using something similar to MesseFormat patterns. Do you think those would help?

**Comment by kajmagnus** [comment]
Oh I meant Portuguese :- )

Encoding in the source code itself:  Hmm, yes there are probably some places where that could be improved. At the same time, that can make the source code a tiny bit harder to read, instead, because then there'll be `' ' + .... + '?'` here and there in the source. I think that's one reason I included the spaces in the translation strings instead.

About using sth like MessageFormat: Yes that seemed like a good idea to me too. In fact I had a look at M.F. and other alternatives maybe half a year ago, and eventually opted for Typescript instead ... and this is what I wrote in a "decisions" document I have: (so I remember why I did things the way I did)

> Translations:
>   Write in Typescript, compile to Javascript. Why?
>   - Applying a translation is then super fast, just object lookup: `Button({}, t.Reply)`.
>   - No dependencies: All translation libs I found were >= 6kb min.js.gz, which is fairly much when trying to keep the slim-bundle < 150 kb.
>   - No dependencies: The developers don't need to read about & undrestand a translation lib and how to pre-compilation integrate it.
>   - Typesafe. The Typescript compiler checks all translation files: that no fields are missing, that there are no extra fields, and that the fields referenced from the React components actually exists & spelled properly.
>
>Drawbacks:
>   - People who translate, will sometimes need to be able to read-and-understand how an if statement works, or `text + number`. Maybe this excludes 50%? of the population from translating Talkyard. That's fine — if someone cannot understand if statements, just wait until someone else, who can, wants to translate. — It's more important to keep things simple for the developers, I think. They're the ones who are totally short of time.
>

**Comment by kajmagnus** [comment]
Hi again @cleydyr  I just merged the PR. Thanks for the contribution :- )

I'm thinking about adding a Git submodule with a little bit info about people who have contributed, if they're okay with being mentioned. I've seen some other projects here have that, e.g. if you scroll down to the bottom of this page:

https://github.com/webscopeio/react-textarea-autocomplete

If you have any thoughts about this, it'd be interesting to hear

(It'd be in a submodule, so one can rewrite history, if someone wants to remove info about him/herself also from old commits. Rewriting history in a submodule shouldn't cause too many problems for others, hmm.)

(B.t.w. the Typescript compiler just helped me find a missing translation value — namely a field I added recently and forgot about:  (I translated it to Portuguese via Google Translate, I hope it's correct (?))

```
     VerifiedDot: "Verificado. ",	     VerifiedDot: "Verificado. ",
+    NotVerifiedDot: "Não verificado. ",  // was [google-translate]
```
)

**Comment by cleydyr** [comment]
Hi, @kajmagnus.

I'm glad my contribution has been accepted. And the missing translation machine-translated looks fine for me. Question: is the Docker image already updated with the pt-BR language? I'm deploying it and wanted to see how it looks.

Regarding the decisions about the translations, I see day after day that Javascript development is a totally different beast from the heavyweight Java EE world from where I'm coming. XD It makes sense, though.

**Comment by kajmagnus** [comment]
Hi @cleydyr, I haven't updated the image. Right now I'm writing end-to-end tests for bug fixes & admin user list & view-user improvements. I would think later this week, maybe on Saturday or Sunday, it'll be ready.

JavaEE & JS: yes,  hmm, and in a way, Javascript can maybe remind a little bit of embedded programming, in the sense that one tries to fit lots of functionality / code, in not-too-manky-kilobyte :- )

**Comment by kajmagnus** [comment]
( @cleydyr Sorry for taking a while with the new version & language. During the last weeks, I did some improvements / bug fixes related the Admin-Area Review page, and last week I started writing end-to-end tests for that, and found some more things to fix, and this has taken a bit longer than what I thought. — I would think, a new version, in about 3 days.)

**Comment by kajmagnus** [comment]
( @cleydyr  I've deployed the changes to Talkyard\.io now — seems to work fine (Portuguese + the other things I changed/fixed). I'm just waiting one or two more days, before publishing the changes to the Docker images everyone else uses .... I do that a little bit later, so I get the chance to first notice any problems myself, at Talkyard\.io.  )

**Comment by kajmagnus** [comment]
B.t.w. if you want to see how it looks now directly, you can create a test site here:  https://www.talkyard.net/-/create-test-site

One thing that comes to my mind, is that the "Recently viewed" text, is a bit wide, i Portuguese — maybe it'd be better, to just change to "Recent" instead.  That text appear in the left hand sidebar, at the top. (It's not intended to drop below the `x` button)

**Comment by cleydyr** [comment]
Hey, @kajmagnus. Thanks for the instructions on how to see the new test forum. I've created one and changed the language to Portuguese (Brazilian) it looks good. I noticed some points already that could be improved.

1. The admin guide on the right-hand sidebar is all in English (only the title is translated); there are other places without translation as well.
2. "Nenhum" varies with the gender in Portuguese. So below "chats associados" "nenhum" is the correct form, but below "mensagens diretas" it should be "nenhum**a**" instead (because "mensagem" is a female noun in Portuguese). How can we proceed to prevent that?

Thank!

**Comment by kajmagnus** [comment]
Hi @cleydyr 

1\) Actually, all staff-only things are currently in English. I'd like to have staff-only things in English the nearest time, 1) to save time (I'll be updating the staff area a lot more than non-staff parts of the app, so fairly much more work, to keep translations up-to-date, for the staff-only parts). And also 2) so it's simpler for me to understand what people are talking about, when they submit bugs/ideas related about admin related functionality. (Which can be a bit complicated, in comparison to available-for-everyone parts of the app.)

Translations missings at some other places: Yes I'm going to add more translation fields now soon. (Sorry for not having done that earlier.)

2\) "Nenhum". That's interesting. Instead of only `t: { ... None: "Nenhum" ... }`, i.e. the same `t.None` for *all* None everywhere,

there could be:  `NoDirMsgs: "Nenhuma", // meaning: "No direct messages`

and:  `NoChats: "Nenhum",  // meaning: "No chat channels"`

And, as you can see above, the context for the translation, can be in a comment on the same line (or line above), so people can decide which gender to use, in their case (their language).

Your thoughts about all this?

B.t.w. I think I should close this Git Hub issues section, so people can instead post bugs and things over at Talkyard\.io. Then everything will be in one single place ... so it'll be easier for others to find this discussion about languages and geneders for example. — I'll wait until we're done with these discussions though. (If have any thoughts about this, would be interesting to hear.)

**Comment by cleydyr** [comment]
Hey, @kajmagnus. It seems okay to go that way for now, giving more context on the translation key and on a comment. I can't think of a better way of doing that now.

It's okay to take the discussions to talkyard.io. It will be a way to increase test-driving for the tool on a live environment and Github issues provides pretty much the same functionality.

**Comment by kajmagnus** [comment]
I've added more translation fields. I'll send you an invite to a topic about translations, over at Talkayrd, if that's ok with you?

**Comment by cleydyr** [comment]
Sure, @kajmagnus. Send me an invite and I'll be happy to contribute with the translations.

Regards.
