### ISSUE TITLE
Notify users via e-mail when they are mentioned

### ISSUE THREAD

**Issue by melanopsis** [debiki/talkyard#33]
It would be really useful to notify users via e-mail when they are mentioned in a conversation. 

Thank you.

**Comment by kajmagnus** [comment]
@melanopsis They do get notified via email, if `@mentioned` — or should be at least. I'm wondering if maybe they don't get notified, beause there's somehow a `.` (dot) in the username? What's the user's usename?

As of right now, that's not supported: the software wouldn't understand that `this @ment.ion mentions` a user named `men.tion` — it'd instead lookup user `ment` and see that there's no such user, and then don't send any email.

**Comment by melanopsis** [comment]
I've just tested this one more time and mentioning usernames without `.` seems to be working fine which wasn't the case before. I am not sure what the issue was then, sorry for the false alarm. I'm going to close this since my only issue was really #34

**Comment by kajmagnus** [comment]
Ok thanks for the update. If happens again, it'd be interesting to know :- )

**Comment by kajmagnus** [comment]
B.t.w. I'm planning to close this *Issues* section in GitHub, and move bug reports & things to the forum over at Talkyard\.io — then, people who don't visit GitHub, also get to know about bugs & ideas that otherwise would have been visible here at GitHub only.

So if you want to submit more issues, you might want to do that at Talkyard\.io instead (because the ones here will somewhat soon become 404 Not Found)
